// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    [Migration("20220503170904_teams-expansion")]
    partial class teamsexpansion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("LeaguePosition")
                        .HasColumnType("int");

                    b.Property<int>("SeasonDrawn")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("SeasonLost")
                        .HasColumnType("int");

                    b.Property<int>("SeasonPlayed")
                        .HasColumnType("int");

                    b.Property<int>("SeasonPoints")
                        .HasColumnType("int");

                    b.Property<int>("SeasonWon")
                        .HasColumnType("int");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalDrawn")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("TotalLost")
                        .HasColumnType("int");

                    b.Property<int>("TotalPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalWon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
