export interface Team {
  id: string,
  teamName: string,
  abbreviation: string,
  sponsor: string,
  seasonPlayed: number,
  seasonWon: number,
  seasonDrawn: number,
  seasonLost: number,
  seasonGoalsFor: number,
  seasonGoalsAgainst: number,
  seasonGoalDifference: number,
  seasonPoints: number,
  totalPlayed: number,
  totalWon: number,
  totalDrawn: number,
  totalLost: number,
  totalGoalsFor: number,
  totalGoalsAgainst: number,
  totalGoalDifference: number,
  totalPoints: number,
  leaguePosition: number
}
